version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package.json" }}
    paths:
      - ~/meta-schema/node_modules

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|dependabot|fix|feat)\/.*$/

defaults: &defaults
  working_directory: ~/meta-schema

jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm install codecov
      - run: npm test
      - run: ./node_modules/.bin/codecov
      - save_cache: *save-deps-cache

  test-go:
    <<: *defaults
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go test .

  build:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm run build
      - save_cache: *save-deps-cache

  release:
    <<: *defaults
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.18.4/node-v12.18.4-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.18.4-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run: npm install
      - run: npm run build
      - run: ./node_modules/.bin/semantic-release
      - run: ls
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 mv src/schema.json s3://meta.open-rpc.org/latest.json
      - run:
          name: invalidate cloudfront
          command: aws cloudfront create-invalidation --distribution-id E2TNH97Q34RX9Z --paths '/*'
      - save_cache: *save-deps-cache

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr
      - test-go:
          filters: *filter-only-semantic-pr
      - build:
          filters: *filter-only-semantic-pr

  release:
    jobs:
      - test:
          filters: *filter-only-master
      - test-go:
          filters: *filter-only-master
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - test
            - test-go
            - build
      - release:
          filters: *filter-only-master
          context: open-rpc-deployer
          requires:
            - hold
